### ISSUE TITLE
Impossible to change speed in animation plot on Windows: ValueError

### ISSUE THREAD

**Issue by TatianaKLM** [stcorp/visan#1]
Hello!

When I am trying to change speed of animation in the plot created by wplot(), I am getting an error:

```
Traceback (most recent call last):
  File "C:\Users\Tatiana\Anaconda3\lib\site-packages\visan\plot\animationtoolbar.py", line 241, in OnSpeed
    self.SetFPS(event.GetString())
  File "C:\Users\Tatiana\Anaconda3\lib\site-packages\visan\plot\animationtoolbar.py", line 165, in SetFPS
    self.interval = int((1.0 / float(fps)) * 1000.0)
ValueError: could not convert string to float: 
  File "C:\Users\Tatiana\Anaconda3\lib\site-packages\visan\plot\animationtoolbar.py", line 241, in OnSpeed
    self.SetFPS(event.GetString())
  File "C:\Users\Tatiana\Anaconda3\lib\site-packages\visan\plot\animationtoolbar.py", line 165, in SetFPS
    self.interval = int((1.0 / float(fps)) * 1000.0)
ValueError: could not convert string to float: 

```

This happens both when I use arrows to increment/decrement by one and when I enter the number myself.

The version of VISAN is the following:
`VISAN 4.0 (Python 3.7.4, wxPython 4.0.4, VTK 8.2.0, NumPy 1.16.5, CODA 2.21, HARP 1.9.2)`

I have Windows 10 Professional

Thank you in advance!

**Comment by svniemeijer** [comment]
Thanks for the bug report. This was an issue with the way we were handling spincontrol events.
It has been fixed in 374ffdb32fa1adb978d2504d0411eb268e49bfe3
